(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["MyStyle`DataAnalysis`"];


powerSpectrum::usage="powerSpectrum[data, timeSpan] returns the power spectrum of data set data.";


Begin["`Private`"];


Unprotect[powerSpectrum];
powerSpectrum[data_List,timeSpan_]:=Module[{},Thread[List[Range[1,Length[#]]*(2Pi/timeSpan),#]]&[(#[[2;;Ceiling[Length[#]/2]]]&@Abs[Fourier[data]]^2)]];
Protect[powerSpectrum];


End[];(*End `Private` Context.*)


EndPackage[];
